spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/test
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    primary:  true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
server:
  port: 8888
